Windows 7 notifications
electron/brightray pull request #279
Opened 2017-03-16 13:03 UTC by alespergl

This is the implementation of desktop notifications for Windows 7.

Resolves [electron #8384](https://github.com/electron/electron/issues/8384)

2017-03-16 13:38 UTC, alespergl commented
@electron/maintainers Looking for reviewers for this. Thanks

2017-03-16 18:26 UTC, poiru commented on browser/win/notification_presenter_win.cc
> +  if (version < base::win::VERSION_WIN7)
Chrome 50 dropped support for Vista so this check isn't strictly needed.

2017-03-16 18:28 UTC, poiru commented on browser/win/win32_desktop_notifications/common.h
> +    std::wstring bodyText;
We use `snake_case` elsewhere in the codebase. Could you use snake case here and elsewhere?

2017-03-17 18:42 UTC, felixrieseberg commented
:bow: Thank you so much for this mountain of work. Tons of people will be very happy - I'll try to take a quick look on Monday.

2017-03-20 22:17 UTC, zcbenz commented
Does the code under `browser/win/win32_desktop_notifications` come from an existing library? It seems that the implementation is glueing an library instead of writing everything from scratch.

2017-03-20 23:57 UTC, alespergl commented
No, it's 100% new code. That part under the subdirectory is functionally independent, that's maybe why it looks like a separate library - it's structured that way.

2017-03-23 22:19 UTC, felixrieseberg commented
This looks 👏 really good. As discussed in person, I'm so very happy we have this PR. Thank you so much! I have only three requests:

:one: As mentioned by @poiru, snake_case would be a good change.
:two: We frequently fail to send notifications using the native `ToastNotifier` in Windows 8, 8.1, and 10. I would love an option to use this notification object even from versions newer than Windows 7.
:three: I'd love to be able to configure the background color.

Both 2 and 3 could easily be another PR in the future.

2017-03-23 22:20 UTC, felixrieseberg requested changes
`snake_case`, otherwise 👍 💯

2017-03-24 16:02 UTC, alespergl commented
I will post an update with snake casing later. I also have a fix for a small DPI related bug that I discovered, but I still need to test it in a multi-monitor setup.

We should think more about the right approach for explicitly selecting the type of notification from the calling code. First thing that comes to mind is consistency across non-Windows OSes. But I do support the general idea.

The color is now derived from the one which the user has selected for windows in the Control Panel. I see some value in being able to change it (e.g. to add category classification). Still, we should give it a bit more thought to make sure the feature doesn't make the user's desktop a playground for every app developer's creativity.

Which brings me to an issue which should be addressed as well at some point - this currently doesn't consider a scenario where multiple Electron apps generate notifications at the same time. Right now these would simply overlap each other.

2017-03-27 16:20 UTC, kevinsawicki commented
https://github.com/electron/brightray/pull/285 has been merged which enables `cpplint` on CI builds so if you rebase/merge master it should pull in those changes.

2017-03-28 09:45 UTC, alespergl commented on browser/notification_presenter.cc
> +  if (!notification) return {};
We're not calling `new` here and `CreateNotificationObject` could return null depending on the implementation, so it's safer to check for it. Alternatively (if we say the return value must not be null) there should at least be an assertion check.

2017-03-29 04:36 UTC, zcbenz commented on browser/notification_presenter.cc
> +  if (!notification) return {};
Current design is, if a platform does not have a implementation then we do not create a `NotificationPresenter` at all (i.e. returning null in `GetNotificationPresenter`), and if an error happens when creating the native notification, `NotificationFailed` would be called.

So  `CreateNotificationObject` is guaranteed to return a `Notification` object with `new`, and doing assertion would be unnecessary since failed `new` would simply crash.

2017-04-01 21:09 UTC, akashnimare commented
Any progress on this @alespergl 🤗

2017-04-11 06:06 UTC, zcbenz commented
Thanks!

2017-04-11 06:06 UTC, merged

2018-11-08 09:03 UTC, RukaiYu commented
Hello @alespergl,
Thanks for the great work on this feature.

Could this part of code ported to a single module that can be used in C#?

I'm working on another project in windows forms, which needs to send a notification on windows 7. And I found your solution is the greatest one.

Could you give me some guides/tips to do that?
Thank you very much!